# config/doctrine/Configuration.orm.yml
App\ReaccionEstudio\ReaccionCMSBundle\Entity\Configuration:
    type: entity
    table: config
    repositoryClass: App\ReaccionEstudio\ReaccionCMSBundle\Repository\ConfigurationRepository

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:

        name:
            type: string
            length: 255
         
        value:
            type: text
        
        type:
            type: string
            length: 255
            nullable: true

        required:
            type: boolean
            nullable: true

        value_options:
            type: text
            nullable: true

        groups:
            type: text
            nullable: true

    lifecycleCallbacks: 
