# config/doctrine/Content.orm.yml
App\ReaccionEstudio\ReaccionCMSBundle\Entity\Content:
    type: entity
    table: contents
    repositoryClass: App\ReaccionEstudio\ReaccionCMSBundle\Repository\ContentRepository

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:

        key:
            type: string
            length: 255

        value:
            type: text
            nullable: true

        type:
            type: string
            length: 255

        position:
            type: integer
            length: 3

        isEnabled:
            type: boolean

        createdAt:
            type: datetime

        updatedAt:
            type: datetime
            nullable: true

    lifecycleCallbacks: 
        prePersist: [ setCreatedValue ]
        preUpdate: [ setUpdatedValue ]
