# config/doctrine/Media.orm.yml
App\ReaccionEstudio\ReaccionCMSBundle\Entity\Media:
    type: entity
    table: media
    repositoryClass: App\ReaccionEstudio\ReaccionCMSBundle\Repository\MediaRepository

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        
        name:
            type: string
            length: 255
        
        path:
            type: string
            length: 255
        
        large_path:
            type: string
            length: 255
            nullable: true
        
        medium_path:
            type: string
            length: 255
            nullable: true
        
        small_path:
            type: string
            length: 255
            nullable: true
        
        size:
            type: decimal
        
        large_size:
            type: decimal
            nullable: true
        
        medium_size:
            type: decimal
            nullable: true
        
        small_size:
            type: decimal
            nullable: true

        mimetype:
            type: string
            length: 255

        createdAt:
            type: datetime

    lifecycleCallbacks: 
        prePersist: [ setCreatedValue ]
