# config/doctrine/Menu.orm.yml
App\ReaccionEstudio\ReaccionCMSBundle\Entity\Menu:
    type: entity
    table: menu
    repositoryClass: App\ReaccionEstudio\ReaccionCMSBundle\Repository\MenuRepository

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        
        name:
            type: string
            length: 255
        
        slug:
            type: string
            length: 255

        language:
            type: string
            column: language
            options:
                default: 'en'

        enabled:
            type: boolean
        
        createdAt:
            type: datetime
        
        updatedAt:
            type: datetime
            nullable: true

    lifecycleCallbacks: 
        prePersist: [ setCreatedValue, setUpdatedValue ]
        preUpdate: [ setUpdatedValue ]