# config/doctrine/Menu.orm.yml
App\ReaccionEstudio\ReaccionCMSBundle\Entity\Menu:
    type: entity
    table: menu
    repositoryClass: App\ReaccionEstudio\ReaccionCMSBundle\Repository\MenuRepository

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    manyToOne:

        parent:
          targetEntity: App\ReaccionEstudio\ReaccionCMSBundle\Entity\Menu
          joinColumn:
            name: parent_id
            referencedColumnName: id
            onDelete: CASCADE

    fields:
        
        name:
            type: string
            length: 255
        
        type:
            type: string
            length: 255
        
        value:
            type: string
            length: 255
        
        target:
            type: string
            length: 6
        
        position:
            type: integer
            length: 2

        enabled:
            type: boolean

    lifecycleCallbacks: 

