# config/doctrine/Page.orm.yml
ReaccionEstudio\ReaccionCMSBundle\Entity\Page:
    type: entity
    table: pages
    repositoryClass: ReaccionEstudio\ReaccionCMSBundle\Repository\PageRepository

    oneToMany:
        content:
            targetEntity: ReaccionEstudio\ReaccionCMSBundle\Entity\PageContent
            mappedBy: page
    
    manyToOne:

        translationGroup:
          targetEntity: ReaccionEstudio\ReaccionCMSBundle\Entity\PageTranslationGroup
          inversedBy: pages
          joinColumn:
            name: translation_group_id
            referencedColumnName: id
            onDelete: SET NULL

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        
        name:
            type: string
            length: 255
        
        slug:
            type: string
            length: 255
        
        enabled:
            type: boolean

        type:
            type: string
            length: 255
            nullable: true
        
        mainPage:
            type: boolean
            nullable: true

        language:
            type: string
            column: language
            options:
                default: 'en'

        templateView:
            type: string
            length: 255

        options:
            type: text
            nullable: true

        seoTitle:
            type: string
            length: 255
            nullable: true
        
        seoDescription:
            type: text
            nullable: true
        
        seoKeywords:
            type: string
            length: 255
            nullable: true

        createdAt:
            type: datetime
        
        updatedAt:
            type: datetime
            nullable: true

    lifecycleCallbacks: 
        prePersist: [ setCreatedValue, setUpdatedValue ]
        preUpdate: [ setUpdatedValue ]
