# config/doctrine/PageContent.orm.yml
ReaccionEstudio\ReaccionCMSBundle\Entity\PageContent:
    type: entity
    table: pages_content
    repositoryClass: ReaccionEstudio\ReaccionCMSBundle\Repository\PageContentRepository

    manyToOne:

        page:
          targetEntity: ReaccionEstudio\ReaccionCMSBundle\Entity\Page
          inversedBy: content
          joinColumn:
            name: page_id
            referencedColumnName: id
            onDelete: CASCADE

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:

        name:
            type: text
            nullable: true

        slug:
            type: string
            length: 255

        value:
            type: text
            nullable: true

        type:
            type: string
            length: 255

        position:
            type: integer
            length: 3

        isEnabled:
            type: boolean

        options:
            type: text
            nullable: true

        createdAt:
            type: datetime

        updatedAt:
            type: datetime
            nullable: true

    lifecycleCallbacks: 
        prePersist: [ setCreatedValue, setUpdatedValue ]
        preUpdate: [ setUpdatedValue ]
