# config/doctrine/PageContent.orm.yml
App\ReaccionEstudio\ReaccionCMSBundle\Entity\PageContent:
    type: entity
    table: pages_content
    repositoryClass: App\ReaccionEstudio\ReaccionCMSBundle\Repository\PageContentRepository

    manyToOne:

        page:
          targetEntity: App\ReaccionEstudio\ReaccionCMSBundle\Entity\Page
          joinColumn:
            name: page_id
            referencedColumnName: id

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:

        value:
            type: text
            nullable: true

        type:
            type: string
            length: 255

        position:
            type: integer
            length: 3

        isEnabled:
            type: boolean

        createdAt:
            type: datetime

        updatedAt:
            type: datetime
            nullable: true

    lifecycleCallbacks: 
        prePersist: [ setCreatedValue, setUpdatedValue ]
        preUpdate: [ setUpdatedValue ]
