# config/doctrine/User.orm.yml
ReaccionEstudio\ReaccionCMSBundle\Entity\User:
    type:  entity
    table: user
    repositoryClass: ReaccionEstudio\ReaccionCMSBundle\Repository\UserRepository
    
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:

        language:
            type: string
            column: language
            options:
                default: 'en'

        nickname:
            type: string
            column: nickname
            nullable: true
