index:
    path: /
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\IndexController::index

index_slug:
    path: /{slug}(?!/admin)
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\IndexController::index
