index:
    path: /
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\IndexController::index

index_slug:
    path: /{slug}
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\IndexController::index
    requirements:
      slug:  "^(?!admin).+"
