index:
    path: /
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\IndexController::index

# blog
blog:
    path: /blog/{page}
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\EntriesController::index
    defaults: { page: 1 }
    requirements:
      page: \d+

blog_category:
    path: /blog/category/{category}/{page}
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\EntriesController::category
    defaults: { page: 1 }
    requirements:
      page: \d+

blog_tag:
    path: /blog/tag/{tag}/{page}
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\EntriesController::tag
    defaults: { page: 1 }
    requirements:
      page: \d+

# comments
post_comment:
    path: /entry/{entry}/comment/add
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\CommentController::post

post_comment_reply:
    path: /entry/comment/{comment}/update
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\CommentController::postReply
    options:
        expose: true

update_comment:
    path: /entry/comment/{comment}/update
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\CommentController::update
    options:
        expose: true

remove_comment:
    path: /entry/comment/{comment}/remove
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\CommentController::remove

# users
user_register:
    path: /register
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\UserController::register

user_login:
    path: /login
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\UserController::login

# languages
change_language:
    path: /change_language/{language}
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\LanguageController::index
    options:
        expose: true

# pages
index_slug:
    path: /{slug}
    controller: App\ReaccionEstudio\ReaccionCMSBundle\Controller\IndexController::index
    requirements:
      slug:  "^(?!admin).+"