# rocket_theme/config.yaml
theme_config:
  folder_name: 'rocket_theme'
  name: 'Rocket Theme'
  description: 'Rocket Theme is the ReaccionCMS default theme.'
  keywords: 'rocket, simple, reaccion'
  version: 0.1
  author: 'Alberto Vian'
  email: 'alberto@reaccionestudio.com'
  website: 'https://www.reaccionestudio.com'
  preview_image: 'images/reaccion_estudio.png'
  views:
    page: 'page.html.twig'
    navigation: 'layout/navigation.html.twig'
    menu: 'layout/menu.html.twig'
    footer: 'layout/footer.html.twig'
    404_error: '404_error.html.twig'
    500_error: '500_error.html.twig'